# Generated by Django 4.1.2 on 2023-04-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('diabetes', models.CharField(blank=True, choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2')], max_length=6, null=True)),
                ('blood_glucose_level', models.DecimalField(decimal_places=2, max_digits=6)),
                ('blood_pressure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('physical_activity_daily', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dietary_restriction', models.CharField(blank=True, choices=[('Egg', 'Egg'), ('Red Meat', 'Red Meat'), ('Fish', 'Fish'), ('Milk', 'Milk')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_management.user')),
            ],
        ),
    ]
