# Generated by Django 4.1.2 on 2023-04-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='blood_glucose_level',
            new_name='cholesterol_level',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='physical_activity_daily',
            new_name='glucose_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='diabetes',
        ),
        migrations.AddField(
            model_name='profile',
            name='physical_activity',
            field=models.DecimalField(decimal_places=2, default=210, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
