# Generated by Django 4.1.2 on 2023-04-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_profile_height_alter_profile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dietary_restriction',
            field=models.CharField(choices=[('Egg', 'Egg'), ('Red Meat', 'Red Meat'), ('Fish', 'Fish'), ('Milk', 'Milk'), ('None', 'None')], max_length=10),
        ),
    ]
