# Generated by Django 4.1.2 on 2023-04-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_profile_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='physical_activity',
            field=models.DecimalField(choices=[('sedentary_lifestyle', 1.4), ('low_active_lifestyle', 1.6), ('moderate_lifestyle', 1.8), ('active_lifestyle', 2.0), ('very_active_lifestyle', 2.2)], decimal_places=1, max_digits=2),
        ),
    ]
