# Generated by Django 4.1.2 on 2023-04-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('groups', models.CharField(max_length=10)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saturated_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cholesterol', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sugars', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category1', models.CharField(blank=True, max_length=20, null=True)),
                ('category2', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
