# Generated by Django 4.1.2 on 2023-04-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_management', '0002_breakfast_meal_dinner_meal_lunch_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_food1', models.CharField(max_length=200)),
                ('breakfast_food2', models.CharField(max_length=200)),
                ('breakfast_food3', models.CharField(max_length=200)),
                ('lunch_food1', models.CharField(max_length=200)),
                ('lunch_food2', models.CharField(max_length=200)),
                ('lunch_food3', models.CharField(max_length=200)),
                ('dinner_food1', models.CharField(max_length=200)),
                ('dinner_food2', models.CharField(max_length=200)),
                ('dinner_food3', models.CharField(max_length=200)),
                ('total_calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_cholesterol', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_carbohydrates', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_fiber', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_sugars', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
