# Generated by Django 4.1.2 on 2023-04-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_management', '0004_lunchmealfeedback_dinnermealfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast_meal',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dinner_meal',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunch_meal',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
