# Generated by Django 4.1.2 on 2023-05-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_management', '0005_breakfast_meal_score_dinner_meal_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day_meal',
        ),
        migrations.RemoveField(
            model_name='breakfast_meal',
            name='score',
        ),
        migrations.RemoveField(
            model_name='dinner_meal',
            name='score',
        ),
        migrations.RemoveField(
            model_name='lunch_meal',
            name='score',
        ),
    ]
