# Generated by Django 4.1.2 on 2023-05-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_management', '0006_delete_day_meal_remove_breakfast_meal_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast_meal',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dinner_meal',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lunch_meal',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
